spring.application.name=pos
# Db cofigurations start
spring.datasource.url=jdbc:postgresql://localhost:5432/pos
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Db config end

spring.flyway.enabled=true