spring:
  application:
    name: pos

  profiles:
    active: dev

server:
  port: 8080

app:
  jwt:
    issuer: pos-api
    secret: ${APP_JWT_SECRET:pos-development-secret-key-pos-development-secret-key}
    access-token-expiration: 15m
